###worker 1
POST http://localhost:8080/api/v0/list
Content-Type: application/json

{
  "full_name": "Vasya Bondarev Alev",
  "passport": 7878,
  "is_employee": true,
  "actual_company": "yandex",
  "reason": "not null"
}

###worker 2
POST http://localhost:8080/api/v0/list
Content-Type: application/json

{
  "full_name": "Semen Vasilievich Gordeev",
  "passport": 7356,
  "is_employee": true,
  "actual_company": "yandex",
  "reason": "not null"
}

###worker 3
POST http://localhost:8080/api/v0/list
Content-Type: application/json

{
  "full_name": "Весёлкин Филон Прович",
  "passport": 7545987,
  "is_employee": true,
  "actual_company": "tatneft",
  "reason": "not null"
}

###worker 4
POST http://localhost:8080/api/v0/list
Content-Type: application/json

{
  "full_name": "Навроцкий Валериан Викулович",
  "passport": 23572364,
  "is_employee": true,
  "actual_company": "tatneft",
  "reason": "drunk"
}